cmake_minimum_required(VERSION 3.20)
project(tooltipsonde LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_AUTOMOC ON)
find_package(ECM REQUIRED NO_MODULE)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
find_package(Qt6 REQUIRED COMPONENTS Widgets)
find_package(KF6 REQUIRED COMPONENTS I18n WidgetsAddons Config XmlGui)
add_executable(tooltipsonde tooltipsonde.cpp)
target_link_libraries(tooltipsonde Qt6::Widgets KF6::I18n KF6::WidgetsAddons KF6::ConfigGui KF6::XmlGui)
add_executable(tooltipsonde2 tooltipsonde2.cpp)
target_link_libraries(tooltipsonde2 Qt6::Widgets KF6::I18n KF6::WidgetsAddons KF6::ConfigGui KF6::XmlGui)
add_executable(tooltipsonde3 tooltipsonde3.cpp)
target_link_libraries(tooltipsonde3 Qt6::Widgets)
