cmake_minimum_required(VERSION 3.20)
project(dirsprobe NONE)
find_package(ECM REQUIRED NO_MODULE)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
include(KDEInstallDirs)
message(STATUS "KDE_INSTALL_METAINFODIR      = ${KDE_INSTALL_METAINFODIR}")
message(STATUS "KDE_INSTALL_FULL_METAINFODIR = ${KDE_INSTALL_FULL_METAINFODIR}")
message(STATUS "KDE_INSTALL_FULL_APPDIR      = ${KDE_INSTALL_FULL_APPDIR}")
message(STATUS "CMAKE_INSTALL_PREFIX         = ${CMAKE_INSTALL_PREFIX}")
